#!/usr/bin/php
<?php
	
	require('/var/www/_af/main.php');

	$siteDir = './site/';
	$baseDir = '/var/www/production/skeljs.org/htdocs/';

	chdir($siteDir);

	// Setup
		$cmds = array(
			'rm -rf ' . $baseDir . '*',
			'cp -RL assets ' . $baseDir,
			'cp -RL example ' . $baseDir,
			'cp -RL files ' . $baseDir,
			'php index.php > ' . $baseDir . '/index.html'
		);

		foreach ($cmds as $cmd)
			exec($cmd);

	// index.html
		$fn = $baseDir . 'index.html';
		$s = file_get_contents($fn);
		file_put_contents($fn, afu_String::minimizeMarkup($s));

	// assets/js/config.js
		$fn = $baseDir . 'assets/js/config.js';
		$s = file_get_contents($fn);
		file_put_contents($fn, afu_String::minimizeJS($s));

	// CSS
		$a = afu_File::getFileList($baseDir . 'assets/css/', '@\.css$@', true);
		
		foreach ($a as $fn)
		{
			$s = file_get_contents($fn);
			file_put_contents($fn, afu_String::minimizeCSS($s));
		}

	// files/example.zip
		exec('zip -q -r -9 ' . $baseDir . 'files/example.zip example/');

?>
